// 北京宣传网站 · 数据文件
// 图片全部来自 Wikimedia Commons（CC0 / 公有领域 / CC BY / CC BY-SA），署名见 credits。

window.BJ_DATA = {
  images: {
    hero: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Hall_of_Supreme_Harmony_and_Mid_L-R_gates_%2820241127120000%29.jpg/3840px-Hall_of_Supreme_Harmony_and_Mid_L-R_gates_%2820241127120000%29.jpg",
    spring: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Summer_Palace_Lake_Kunming_Dragon_Boat_%2810563535385%29.jpg/3840px-Summer_Palace_Lake_Kunming_Dragon_Boat_%2810563535385%29.jpg",
    summer: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Lotuses_at_the_Beihai_Park_06.JPG/3840px-Lotuses_at_the_Beihai_Park_06.JPG",
    autumn: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Ginkgo_trees_%2815649028518%29.jpg/3840px-Ginkgo_trees_%2815649028518%29.jpg",
    winter: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/%E9%9B%AA%E5%90%8E%E4%B8%87%E5%AF%BF%E5%B1%B1%E3%80%90%E8%B7%AF%E4%BA%BA%E3%80%91_-_panoramio.jpg/3840px-%E9%9B%AA%E5%90%8E%E4%B8%87%E5%AF%BF%E5%B1%B1%E3%80%90%E8%B7%AF%E4%BA%BA%E3%80%91_-_panoramio.jpg",
    axis_yongding: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Yongdinggate.jpg/3840px-Yongdinggate.jpg",
    axis_qianmen: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Qianmen_Dajie_Walking_Street_and_Qianmen_Gate_%289870535414%29.jpg/3840px-Qianmen_Dajie_Walking_Street_and_Qianmen_Gate_%289870535414%29.jpg",
    axis_tiananmen: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/%E5%A4%A9%E5%AE%89%E9%97%A8%E5%A4%9C%E6%99%AF.jpg/3840px-%E5%A4%A9%E5%AE%89%E9%97%A8%E5%A4%9C%E6%99%AF.jpg",
    axis_gugong: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Gate_of_Divine_Might_%28Forbidden_City%29_2015_October.jpg",
    axis_jingshan: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Forbidden_City_after_snow_%2820200106114559%29.jpg/3840px-Forbidden_City_after_snow_%2820200106114559%29.jpg",
    axis_zhonggulou: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/View_from_Bell_to_Drum_Tower_%2836206746225%29.jpg/3840px-View_from_Bell_to_Drum_Tower_%2836206746225%29.jpg",
    scene_greatwall: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/%E9%87%91%E5%B1%B1%E5%B2%AD%E9%95%BF%E5%9F%8E_-_Jinshanling_Great_Wall_%287837756572%29.jpg/3840px-%E9%87%91%E5%B1%B1%E5%B2%AD%E9%95%BF%E5%9F%8E_-_Jinshanling_Great_Wall_%287837756572%29.jpg",
    scene_tiantan: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Hall_of_Prayer_for_Good_Harvest_full_exterior_view.jpg/3840px-Hall_of_Prayer_for_Good_Harvest_full_exterior_view.jpg",
    scene_yiheyuan: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Seventeen_Arch_Bridge_%2820201221160537%29.jpg/3840px-Seventeen_Arch_Bridge_%2820201221160537%29.jpg",
    scene_hutong: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Beijing_hutong_Wudaoying_1.jpg/3840px-Beijing_hutong_Wudaoying_1.jpg",
    scene_shichahai: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Shichahai_014_boat_west_of_Yinding_Bridge_%2820211008152036%29.jpg/3840px-Shichahai_014_boat_west_of_Yinding_Bridge_%2820211008152036%29.jpg",
    scene_798: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/In_798_Art_Zone_%288006744324%29.jpg/3840px-In_798_Art_Zone_%288006744324%29.jpg",
    scene_birdsnest: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Beijing_national_stadium_4.jpg/3840px-Beijing_national_stadium_4.jpg",
    day_morning: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Beijing_Drum_Tower.jpg/3840px-Beijing_Drum_Tower.jpg",
    day_noon: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Qianmen_Dajie_Walking_Street_and_Qianmen_Gate_%289870535725%29.jpg/3840px-Qianmen_Dajie_Walking_Street_and_Qianmen_Gate_%289870535725%29.jpg",
    day_dusk: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Sunset_on_Tiananmen_Square_%2811512917514%29.jpg/3840px-Sunset_on_Tiananmen_Square_%2811512917514%29.jpg",
    day_night: "https://upload.wikimedia.org/wikipedia/commons/4/40/Houhai_Lake_and_Drum_Tower_Beijing_2015_October.jpg",
  food_kaoya: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Beijing_duck_%2811513422233%29.jpg/3840px-Beijing_duck_%2811513422233%29.jpg",
    food_shuanyangrou: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Instant-boiled_mutton_hot_pot_at_Yangfang_Shengli_%2820200111153612%29.jpg/3840px-Instant-boiled_mutton_hot_pot_at_Yangfang_Shengli_%2820200111153612%29.jpg",
    food_zhizi: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Zhizi_Kaorou%2C_mutton_after_roasting_%2820220219182001%29.jpg/3840px-Zhizi_Kaorou%2C_mutton_after_roasting_%2820220219182001%29.jpg",
    food_jingjiang: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Jingjiang_Rousi_%28saut%C3%A9ed_shredded_pork_in_sweet_bean_sauce%29.jpg/3840px-Jingjiang_Rousi_%28saut%C3%A9ed_shredded_pork_in_sweet_bean_sauce%29.jpg",
    food_ganzha: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Dry-fried_meatballs_%2820220309175011%29.jpg/3840px-Dry-fried_meatballs_%2820220309175011%29.jpg",
    food_jiangzhouzi: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Tian_Fu_Hao%27s_Jiangzhouzi_%2820241112180916%29.jpg/3840px-Tian_Fu_Hao%27s_Jiangzhouzi_%2820241112180916%29.jpg",
    food_tasimi: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Tasimi_at_Shahe_Huayunlou_Restaurant%2C_Beijing_%2820220407122125%29.jpg/3840px-Tasimi_at_Shahe_Huayunlou_Restaurant%2C_Beijing_%2820220407122125%29.jpg",
    food_yangxiezi: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Liangjianrongtian_Lamb_Spine_Hot_Pot_Restaurant%2C_Xi%27erqi_%2820241012123931%29.jpg/3840px-Liangjianrongtian_Lamb_Spine_Hot_Pot_Restaurant%2C_Xi%27erqi_%2820241012123931%29.jpg",
    food_jiemodun: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Cabbage_rolls_in_yellow_mustard_%2820191024191957%29.jpg",
    food_yangza: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Lamb_offal_soup_in_Beijing_%2820190607123906%29.jpg/3840px-Lamb_offal_soup_in_Beijing_%2820190607123906%29.jpg",
    food_zhajiangmian: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/%E5%9B%9B%E5%AD%A3%E6%B0%91%E7%A6%8F%E7%9A%84%E7%82%B8%E9%85%B1%E9%9D%A2.jpg/3840px-%E5%9B%9B%E5%AD%A3%E6%B0%91%E7%A6%8F%E7%9A%84%E7%82%B8%E9%85%B1%E9%9D%A2.jpg",
    food_luzhu: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Luzhu_Huoshao_at_Huangsi_%2820211213162653%29.jpg/3840px-Luzhu_Huoshao_at_Huangsi_%2820211213162653%29.jpg",
    food_chaogan: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Beijing_traditional_breakfast_Chaogan_Youbing.jpg/3840px-Beijing_traditional_breakfast_Chaogan_Youbing.jpg",
    food_baodu: "https://upload.wikimedia.org/wikipedia/commons/9/97/%E7%88%86%E8%82%9A.jpg",
    food_douzhi: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Douzhir_at_Huguosi_Snacks%2C_Beijing_%2820180728170403%29.jpg/3840px-Douzhir_at_Huguosi_Snacks%2C_Beijing_%2820180728170403%29.jpg",
    food_jiaoquan: "https://upload.wikimedia.org/wikipedia/commons/b/bf/%E5%8C%97%E4%BA%AC%E5%B0%8F%E5%90%831.jpg",
    food_mending: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Mending_Roubing_at_Xiangyunxuan%2C_Niujie_%2820220923175329%29.jpg/3840px-Mending_Roubing_at_Xiangyunxuan%2C_Niujie_%2820220923175329%29.jpg",
    food_guanchang: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Pan-fried_mung_bean_starch_sausage_slices_%2820210723133236%29.jpg/3840px-Pan-fried_mung_bean_starch_sausage_slices_%2820210723133236%29.jpg",
    food_wandouhuang: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Pea_flour_cakes_%2820210215172834%29.jpg/3840px-Pea_flour_cakes_%2820210215172834%29.jpg",
    food_lvdagun: "https://upload.wikimedia.org/wikipedia/commons/8/83/Lyu_Da_Gun.jpg",
    food_misandao: "https://upload.wikimedia.org/wikipedia/commons/0/08/Misandao_%281%29.jpg",
    food_kaikouxiao: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Luxihe_sesame_smiley.jpg/3840px-Luxihe_sesame_smiley.jpg",
    food_xingren: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/%E6%9D%8F%E4%BB%81%E8%B1%86%E8%85%90_%286948322744%29.jpg/3840px-%E6%9D%8F%E4%BB%81%E8%B1%86%E8%85%90_%286948322744%29.jpg",
    food_chatang: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Cha_Tang.jpg",
    food_erguotou: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Red_Star_Erguotou_on_shelves_%2820200202160825%29.jpg/3840px-Red_Star_Erguotou_on_shelves_%2820200202160825%29.jpg",
    food_wotou: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Wowotou.jpg",
  },

  seasons: [
    { key: 'spring', name: '春', en: 'SPRING', title: '颐和园 · 昆明湖初醒',
      text: '三月，昆明湖的冰刚化开，第一批画舫从万寿山脚下驶出。玉兰开在乐寿堂前，长廊里的人还穿着薄棉衣。',
      imageKey: 'spring', particle: 'petal' },
    { key: 'summer', name: '夏', en: 'SUMMER', title: '北海 · 荷风十里',
      text: '北海的荷花从六月开到八月。白塔倒在水里，蝉声比钟声还响。傍晚划一条船到琼华岛背面，风是凉的。',
      imageKey: 'summer', particle: 'lotus' },
    { key: 'autumn', name: '秋', en: 'AUTUMN', title: '银杏 · 满城尽带黄金甲',
      text: '北京的秋天来得晚、走得快。十一月的第一场风过后，钓鱼台、地坛、雍和宫的银杏一夜全黄——抬头是金色，低头也是金色。',
      imageKey: 'autumn', particle: 'ginkgo' },
    { key: 'winter', name: '冬', en: 'WINTER', title: '颐和园 · 雪后万寿山',
      text: '一下雪，北京就成了北平。万寿山披上一层白，佛香阁的琉璃瓦只露出一点金，昆明湖静得像一面镜子，把整座山又倒着画了一遍。',
      imageKey: 'winter', particle: 'snow' },
  ],

  timeline: [
    { year: '前1045', era: '燕 · 蓟', seal: '燕', title: '一座城的开始',
      story: '周武王封召公奭于燕，蓟城建在今广安门一带。三千多年前，北京的建城史从这里起笔。' },
    { year: '1153', era: '金 · 中都', seal: '金', title: '第一次成为国都',
      story: '海陵王完颜亮迁都燕京，改称「中都」。北京第一次成为一个王朝的首都，卢沟桥也在这个时代建成。' },
    { year: '1267', era: '元 · 大都', seal: '元', title: '汗八里',
      story: '忽必烈命刘秉忠营建大都，郭守敬凿通惠河，漕船直抵积水潭。马可·波罗在游记里叫它「汗八里」——大汗之城。' },
    { year: '1421', era: '明 · 永乐', seal: '明', title: '紫禁城落成',
      story: '朱棣迁都北京，紫禁城历时十四年建成。三大殿、中轴线、九门城墙——今天北京的骨架，在这一年定型。' },
    { year: '1644', era: '清', seal: '清', title: '三山五园',
      story: '清军入关定都北京。此后两百六十余年，圆明园、颐和园、避暑山庄相继兴建，西郊成了皇家的后花园。' },
    { year: '1925', era: '民国', seal: '民国', title: '故宫向公众打开大门',
      story: '末代皇帝溥仪迁出，故宫博物院成立。五百年来第一次，普通人可以走进紫禁城，看一看皇帝住过的地方。' },
    { year: '1949', era: '新中国', seal: '新', title: '天安门城楼上',
      story: '十月一日，天安门城楼上宣告中华人民共和国成立。北京，再一次成为首都。' },
    { year: '2008', era: '夏奥', seal: '夏奥', title: '二十九个焰火脚印',
      story: '八月八日晚八点，二十九个焰火脚印从永定门沿中轴线一路走到鸟巢。全世界在这一刻看见北京。' },
    { year: '2022', era: '冬奥', seal: '冬奥', title: '双奥之城',
      story: '北京成为世界上第一座既举办过夏季奥运、又举办过冬季奥运的城市。首钢的冷却塔旁，滑雪大跳台腾空而起。' },
  ],

  axis: [
    { name: '永定门', en: 'YONGDINGMEN', note: '中轴线的南起点。7.8 公里的长卷，从这里起笔。', imageKey: 'axis_yongding' },
    { name: '前门', en: 'ZHENGYANGMEN', note: '正阳门，九门之首。箭楼见过驼队，也见过第一列火车。', imageKey: 'axis_qianmen' },
    { name: '天安门', en: 'TIANANMEN', note: '明清的「承天门」，如今是国家的正门。', imageKey: 'axis_tiananmen' },
    { name: '故宫', en: 'THE FORBIDDEN CITY', note: '九千余间房，七十二万平方米，世界上现存最大的木结构宫殿群。', imageKey: 'axis_gugong' },
    { name: '景山', en: 'JINGSHAN', note: '人工堆出的山。站在万春亭上，整条中轴线尽收眼底。', imageKey: 'axis_jingshan' },
    { name: '钟鼓楼', en: 'BELL & DRUM TOWERS', note: '暮鼓晨钟。北京的时间，曾经从这里发出。', imageKey: 'axis_zhonggulou' },
  ],

  scenes: [
    { name: '长城', en: 'Great Wall', imageKey: 'scene_greatwall',
      story: '不到长城非好汉。慕田峪人少，八达岭最壮观，金山岭适合看日出。',
      ticket: '40–45 元', best: '秋季晴天 · 清晨' },
    { name: '天坛', en: 'Temple of Heaven', imageKey: 'scene_tiantan',
      story: '明清皇帝祭天的地方。祈年殿没有一根钉子，回音壁隔着几十米能听见耳语。',
      ticket: '联票 34 元', best: '清晨 · 看晨练的老北京' },
    { name: '颐和园', en: 'Summer Palace', imageKey: 'scene_yiheyuan',
      story: '慈禧的夏宫。长廊 728 米，每一根梁上的画都不重样。冬至前后傍晚，夕阳穿过十七孔桥——「金光穿洞」。',
      ticket: '旺季 30 元', best: '冬至前后 · 傍晚' },
    { name: '胡同', en: 'Hutong', imageKey: 'scene_hutong',
      story: '北京的血管。南锣鼓巷太挤，去五道营、史家胡同，听一听鸽哨。',
      ticket: '免费', best: '午后' },
    { name: '什刹海', en: 'Shichahai', imageKey: 'scene_shichahai',
      story: '前海、后海、西海。夏天划船，冬天滑冰，晚上在银锭桥上看西山。',
      ticket: '免费', best: '夏夜 · 或雪后' },
    { name: '798', en: '798 Art Zone', imageKey: 'scene_798',
      story: '五十年代的电子厂，今天的当代艺术区。包豪斯锯齿厂房里，全是画廊。',
      ticket: '免费（部分展览收费）', best: '周末' },
    { name: '鸟巢', en: "Bird's Nest", imageKey: 'scene_birdsnest',
      story: '2008 与 2022 两届奥运的主会场。夜里亮灯，像一团燃烧的钢铁。',
      ticket: '外观免费 · 入场 50 元', best: '夜晚' },
  ],

  day: [
    { time: '05:30', title: '钟鼓楼 · 晨', text: '天还没亮透，鸽哨先响了。景山上有人在吊嗓子，护城河冒着白气。', imageKey: 'day_morning', bg: '#f3e6cf', ink: '#2a2118' },
    { time: '12:00', title: '前门 · 午', text: '豆汁儿、焦圈、炒肝。老字号门口排队的人，和一百年前一样多。', imageKey: 'day_noon', bg: '#f4efe6', ink: '#1a1a1a' },
    { time: '17:30', title: '景山 · 暮', text: '万春亭上，夕阳把整个紫禁城的琉璃瓦点成金色。这一刻，值得专程来一次。', imageKey: 'day_dusk', bg: '#d9b98a', ink: '#2a1a0e' },
    { time: '21:00', title: '后海 · 夜', text: '酒吧街的灯映在水里，胡同深处有人在拉二胡。北京的夜，从这里开始。', imageKey: 'day_night', bg: '#0b0f1a', ink: '#f4efe6' },
  ],

  credits: [
    { key: "hero", title: "Hall of Supreme Harmony and Mid L-R gates (20241127120000).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Hall%20of%20Supreme%20Harmony%20and%20Mid%20L-R%20gates%20%2820241127120000%29.jpg" },
    { key: "spring", title: "Summer Palace Lake Kunming Dragon Boat (10563535385).jpg", author: "Gary Todd from Xinzheng, China", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Summer%20Palace%20Lake%20Kunming%20Dragon%20Boat%20%2810563535385%29.jpg" },
    { key: "summer", title: "Lotuses at the Beihai Park 06.JPG", author: "Olena Zakharian", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Lotuses%20at%20the%20Beihai%20Park%2006.JPG" },
    { key: "autumn", title: "Ginkgo trees (15649028518).jpg", author: "白士 李", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Ginkgo%20trees%20%2815649028518%29.jpg" },
    { key: "winter", title: "雪后万寿山【路人】 - panoramio.jpg", author: "leej1118bj", license: "CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:%E9%9B%AA%E5%90%8E%E4%B8%87%E5%AF%BF%E5%B1%B1%E3%80%90%E8%B7%AF%E4%BA%BA%E3%80%91%20-%20panoramio.jpg" },
    { key: "axis_yongding", title: "Yongdinggate.jpg", author: "Charlie fong冯成", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Yongdinggate.jpg" },
    { key: "axis_qianmen", title: "Qianmen Dajie Walking Street and Qianmen Gate (9870535414).jpg", author: "Gary Todd from Xinzheng, China", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Qianmen%20Dajie%20Walking%20Street%20and%20Qianmen%20Gate%20%289870535414%29.jpg" },
    { key: "axis_tiananmen", title: "天安门夜景.jpg", author: "Charlie fong冯成", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:%E5%A4%A9%E5%AE%89%E9%97%A8%E5%A4%9C%E6%99%AF.jpg" },
    { key: "axis_gugong", title: "Gate of Divine Might (Forbidden City) 2015 October.jpg", author: "Morio", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Gate%20of%20Divine%20Might%20%28Forbidden%20City%29%202015%20October.jpg" },
    { key: "axis_jingshan", title: "Forbidden City after snow (20200106114559).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Forbidden%20City%20after%20snow%20%2820200106114559%29.jpg" },
    { key: "axis_zhonggulou", title: "View from Bell to Drum Tower (36206746225).jpg", author: "Florian G. from Berlin, Deutschland", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:View%20from%20Bell%20to%20Drum%20Tower%20%2836206746225%29.jpg" },
    { key: "scene_greatwall", title: "金山岭长城 - Jinshanling Great Wall (7837756572).jpg", author: "Nikolaj Potanin from Russia", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:%E9%87%91%E5%B1%B1%E5%B2%AD%E9%95%BF%E5%9F%8E%20-%20Jinshanling%20Great%20Wall%20%287837756572%29.jpg" },
    { key: "scene_tiantan", title: "Hall of Prayer for Good Harvest full exterior view.jpg", author: "Daniel Case", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Hall%20of%20Prayer%20for%20Good%20Harvest%20full%20exterior%20view.jpg" },
    { key: "scene_yiheyuan", title: "Seventeen Arch Bridge (20201221160537).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Seventeen%20Arch%20Bridge%20%2820201221160537%29.jpg" },
    { key: "scene_hutong", title: "Beijing hutong Wudaoying 1.jpg", author: "Andrzej Otrębski", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Beijing%20hutong%20Wudaoying%201.jpg" },
    { key: "scene_shichahai", title: "Shichahai 014 boat west of Yinding Bridge (20211008152036).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Shichahai%20014%20boat%20west%20of%20Yinding%20Bridge%20%2820211008152036%29.jpg" },
    { key: "scene_798", title: "In 798 Art Zone (8006744324).jpg", author: "Nikolaj Potanin from Russia", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:In%20798%20Art%20Zone%20%288006744324%29.jpg" },
    { key: "scene_birdsnest", title: "Beijing national stadium 4.jpg", author: "Arne Müseler", license: "CC BY-SA 3.0 de", page: "https://commons.wikimedia.org/wiki/File:Beijing%20national%20stadium%204.jpg" },
    { key: "day_morning", title: "Beijing Drum Tower.jpg", author: "Toadspike", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Beijing%20Drum%20Tower.jpg" },
    { key: "day_noon", title: "Qianmen Dajie Walking Street and Qianmen Gate (9870535725).jpg", author: "Gary Todd from Xinzheng, China", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Qianmen%20Dajie%20Walking%20Street%20and%20Qianmen%20Gate%20%289870535725%29.jpg" },
    { key: "day_dusk", title: "Sunset on Tiananmen Square (11512917514).jpg", author: "edward stojakovic from Portland, OR, Uni", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Sunset%20on%20Tiananmen%20Square%20%2811512917514%29.jpg" },
    { key: "day_night", title: "Houhai Lake and Drum Tower Beijing 2015 October.jpg", author: "Morio", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Houhai%20Lake%20and%20Drum%20Tower%20Beijing%202015%20October.jpg" },
  { key: "food_kaoya", title: "Beijing duck (11513422233).jpg", author: "pelican from Tokyo, Japan", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Beijing%20duck%20%2811513422233%29.jpg" },
    { key: "food_shuanyangrou", title: "Instant-boiled mutton hot pot at Yangfang Shengli (20200111153612).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Instant-boiled%20mutton%20hot%20pot%20at%20Yangfang%20Shengli%20%2820200111153612%29.jpg" },
    { key: "food_zhizi", title: "Zhizi Kaorou, mutton after roasting (20220219182001).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Zhizi%20Kaorou%2C%20mutton%20after%20roasting%20%2820220219182001%29.jpg" },
    { key: "food_jingjiang", title: "Jingjiang Rousi (sautéed shredded pork in sweet bean sauce).jpg", author: "Zheng Zhou", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Jingjiang%20Rousi%20%28saut%C3%A9ed%20shredded%20pork%20in%20sweet%20bean%20sauce%29.jpg" },
    { key: "food_ganzha", title: "Dry-fried meatballs (20220309175011).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Dry-fried%20meatballs%20%2820220309175011%29.jpg" },
    { key: "food_jiangzhouzi", title: "Tian Fu Hao's Jiangzhouzi (20241112180916).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Tian%20Fu%20Hao%27s%20Jiangzhouzi%20%2820241112180916%29.jpg" },
    { key: "food_tasimi", title: "Tasimi at Shahe Huayunlou Restaurant, Beijing (20220407122125).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Tasimi%20at%20Shahe%20Huayunlou%20Restaurant%2C%20Beijing%20%2820220407122125%29.jpg" },
    { key: "food_yangxiezi", title: "Liangjianrongtian Lamb Spine Hot Pot Restaurant, Xi'erqi (20241012123931).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Liangjianrongtian%20Lamb%20Spine%20Hot%20Pot%20Restaurant%2C%20Xi%27erqi%20%2820241012123931%29.jpg" },
    { key: "food_jiemodun", title: "Cabbage rolls in yellow mustard (20191024191957).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Cabbage%20rolls%20in%20yellow%20mustard%20%2820191024191957%29.jpg" },
    { key: "food_yangza", title: "Lamb offal soup in Beijing (20190607123906).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Lamb%20offal%20soup%20in%20Beijing%20%2820190607123906%29.jpg" },
    { key: "food_zhajiangmian", title: "四季民福的炸酱面.jpg", author: "Liuxingy", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:%E5%9B%9B%E5%AD%A3%E6%B0%91%E7%A6%8F%E7%9A%84%E7%82%B8%E9%85%B1%E9%9D%A2.jpg" },
    { key: "food_luzhu", title: "Luzhu Huoshao at Huangsi (20211213162653).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Luzhu%20Huoshao%20at%20Huangsi%20%2820211213162653%29.jpg" },
    { key: "food_chaogan", title: "Beijing traditional breakfast Chaogan Youbing.jpg", author: "Lixshnew", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Beijing%20traditional%20breakfast%20Chaogan%20Youbing.jpg" },
    { key: "food_baodu", title: "爆肚.jpg", author: "AddisWang", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:%E7%88%86%E8%82%9A.jpg" },
    { key: "food_douzhi", title: "Douzhir at Huguosi Snacks, Beijing (20180728170403).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Douzhir%20at%20Huguosi%20Snacks%2C%20Beijing%20%2820180728170403%29.jpg" },
    { key: "food_jiaoquan", title: "北京小吃1.jpg", author: "AddisWang", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:%E5%8C%97%E4%BA%AC%E5%B0%8F%E5%90%831.jpg" },
    { key: "food_mending", title: "Mending Roubing at Xiangyunxuan, Niujie (20220923175329).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Mending%20Roubing%20at%20Xiangyunxuan%2C%20Niujie%20%2820220923175329%29.jpg" },
    { key: "food_guanchang", title: "Pan-fried mung bean starch sausage slices (20210723133236).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Pan-fried%20mung%20bean%20starch%20sausage%20slices%20%2820210723133236%29.jpg" },
    { key: "food_wandouhuang", title: "Pea flour cakes (20210215172834).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Pea%20flour%20cakes%20%2820210215172834%29.jpg" },
    { key: "food_lvdagun", title: "Lyu Da Gun.jpg", author: "ZhengZhou", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Lyu%20Da%20Gun.jpg" },
    { key: "food_misandao", title: "Misandao (1).jpg", author: "François Nguyen", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Misandao%20%281%29.jpg" },
    { key: "food_kaikouxiao", title: "Luxihe sesame smiley.jpg", author: "Fumikas Sagisavas", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Luxihe%20sesame%20smiley.jpg" },
    { key: "food_xingren", title: "杏仁豆腐 (6948322744).jpg", author: "melanie_ko", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:%E6%9D%8F%E4%BB%81%E8%B1%86%E8%85%90%20%286948322744%29.jpg" },
    { key: "food_chatang", title: "Cha Tang.jpg", author: "Zheng Zhou", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Cha%20Tang.jpg" },
    { key: "food_erguotou", title: "Red Star Erguotou on shelves (20200202160825).jpg", author: "N509FZ", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Red%20Star%20Erguotou%20on%20shelves%20%2820200202160825%29.jpg" },
    { key: "food_wotou", title: "Wowotou.jpg", author: "Fumikas Sagisavas", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Wowotou.jpg" },
  ],

  /* ===== 京味儿 · 美食 ===== */
  foods: [
    { key: 'food_kaoya', name: '北京烤鸭', en: 'Peking Duck', cat: 'main', courage: 1, when: '晚',
      story: '果木挂炉，皮脆如纸。荷叶饼卷上鸭皮、葱丝、甜面酱，一口下去是六百年的宫廷菜。', where: '四季民福 · 全聚德 · 便宜坊' },
    { key: 'food_shuanyangrou', name: '涮羊肉', en: 'Instant-boiled Mutton', cat: 'main', courage: 1, when: '晚',
      story: '铜锅炭火清水涮，手切羊肉七秒即熟，蘸麻酱韭菜花腐乳。北京的冬天是从第一顿涮肉开始的。', where: '东来顺 · 聚宝源 · 南门涮肉' },
    { key: 'food_zhizi', name: '炙子烤肉', en: 'Zhizi Grilled Mutton', cat: 'main', courage: 2, when: '晚',
      story: '铁炙子架在炭火上，羊肉配葱段香菜，一只脚踩在条凳上"武吃"，是清朝八旗子弟留下的吃法。', where: '烤肉季 · 烤肉宛' },
    { key: 'food_jingjiang', name: '京酱肉丝', en: 'Shredded Pork in Sweet Bean Sauce', cat: 'main', courage: 1, when: '午晚',
      story: '六必居的黄酱炒出的肉丝，用豆皮或薄饼卷着葱丝吃。家常，却是北京菜的名片。', where: '大部分京菜馆' },
    { key: 'food_ganzha', name: '干炸丸子', en: 'Dry-fried Meatballs', cat: 'main', courage: 1, when: '午晚',
      story: '外焦里嫩，蘸椒盐。老北京人过年桌上的"四大件"之一，小孩子最惦记的那盘。', where: '同和居 · 峨嵋酒家' },
    { key: 'food_jiangzhouzi', name: '天福号酱肘子', en: 'Braised Pork Knuckle', cat: 'main', courage: 1, when: '午',
      story: '乾隆三年的老字号。肥而不腻，皮糯肉烂，切片夹烧饼是最北京的一顿午饭。', where: '天福号' },
    { key: 'food_tasimi', name: '它似蜜', en: 'Tasimi (Honey-glazed Mutton)', cat: 'main', courage: 2, when: '晚',
      story: '羊肉片裹上甜酱汁，甜中带咸。传说慈禧尝后问"这是什么"，太监答"它似蜜"，从此得名。', where: '鸿宾楼 · 又一顺' },
    { key: 'food_yangxiezi', name: '羊蝎子', en: 'Lamb Spine Hot Pot', cat: 'main', courage: 2, when: '晚',
      story: '羊脊骨形似蝎子，大锅炖到脱骨，啃完骨头再下白菜粉丝。冬夜里最过瘾的一锅。', where: '老诚一锅 · 满恒记' },
    { key: 'food_jiemodun', name: '芥末墩', en: 'Mustard Cabbage Rolls', cat: 'main', courage: 3, when: '午晚',
      story: '白菜心用芥末和糖腌成，一口下去冲得人眼泪直流，然后是脆甜。梁实秋念念不忘的年菜。', where: '老北京家常菜馆' },
    { key: 'food_yangza', name: '羊杂汤', en: 'Lamb Offal Soup', cat: 'main', courage: 3, when: '早',
      story: '羊头肉、羊肚、羊肝切碎，热汤浇上，撒香菜。牛街清晨排队的人，都是为了这一碗。', where: '牛街 · 白记年糕旁' },

    { key: 'food_zhajiangmian', name: '炸酱面', en: 'Zhajiangmian', cat: 'snack', courage: 1, when: '午',
      story: '干黄酱和甜面酱小火炸出来，配八样菜码：黄瓜丝、豆芽、青豆、心里美……北京人家的看家饭。', where: '海碗居 · 方砖厂69号' },
    { key: 'food_luzhu', name: '卤煮火烧', en: 'Luzhu Huoshao', cat: 'snack', courage: 4, when: '午晚',
      story: '猪肠猪肺炸豆腐在老汤里咕嘟着，火烧切井字，浇一勺卤汤。据说是从宫廷"苏造肉"演变的平民版。', where: '小肠陈 · 北新桥卤煮' },
    { key: 'food_chaogan', name: '炒肝', en: 'Chaogan', cat: 'snack', courage: 3, when: '早',
      story: '猪肝猪肠勾芡的浓汤，蒜香扑鼻。老北京吃炒肝不用勺，端着碗转着圈喝。配包子才完整。', where: '姚记炒肝 · 天兴居' },
    { key: 'food_baodu', name: '爆肚', en: 'Quick-boiled Tripe', cat: 'snack', courage: 3, when: '午晚',
      story: '牛羊肚分十几个部位，滚水里几秒钟一爆，蘸麻酱。讲究的是"脆"，多一秒就老。', where: '爆肚冯 · 老门框' },
    { key: 'food_douzhi', name: '豆汁儿', en: 'Douzhir (Fermented Mung Bean Drink)', cat: 'snack', courage: 5, when: '早',
      story: '绿豆发酵的酸馊味，外地人闻风丧胆，北京人一天不喝想得慌。配焦圈和咸菜丝，热着喝。', where: '护国寺小吃 · 老磁器口' },
    { key: 'food_jiaoquan', name: '焦圈', en: 'Jiaoquan (Fried Dough Ring)', cat: 'snack', courage: 1, when: '早',
      story: '油炸的面圈，酥脆掉渣。豆汁儿的官配，也可以夹在烧饼里当早饭。', where: '护国寺小吃' },
    { key: 'food_mending', name: '门钉肉饼', en: 'Mending Roubing', cat: 'snack', courage: 2, when: '午',
      story: '形似城门上的门钉，牛肉大葱馅，一咬一包汤汁。相传慈禧吃了问名字，太监临时编了这个。', where: '牛街 · 宝瑞门钉肉饼' },
    { key: 'food_guanchang', name: '炸灌肠', en: 'Fried Starch Sausage', cat: 'snack', courage: 2, when: '午晚',
      story: '淀粉肠切片煎到焦脆，浇蒜汁，用牙签扎着吃。庙会上的味道。', where: '丰年灌肠 · 隆福寺' },
    { key: 'food_wotou', name: '窝头', en: 'Wotou (Cornmeal Cone)', cat: 'snack', courage: 1, when: '午晚',
      story: '玉米面蒸的锥形馒头。传说慈禧西逃时吃过农家窝头，回宫后让御膳房做小窝头，成了宫廷点心。', where: '仿膳饭庄' },

    { key: 'food_wandouhuang', name: '豌豆黄', en: 'Pea Flour Cake', cat: 'sweet', courage: 1, when: '午',
      story: '豌豆去皮煮烂，加糖凝成金黄的小方块，入口即化。北海仿膳的看家点心，慈禧的最爱。', where: '仿膳饭庄 · 稻香村' },
    { key: 'food_lvdagun', name: '驴打滚', en: 'Lüdagunr (Glutinous Rice Roll)', cat: 'sweet', courage: 1, when: '午',
      story: '黄米面卷豆沙，滚上一层黄豆面，像驴在黄土地上打滚扬起的尘土。', where: '护国寺小吃 · 牛街' },
    { key: 'food_misandao', name: '蜜三刀', en: 'Misandao', cat: 'sweet', courage: 1, when: '午',
      story: '面块上划三刀，油炸后过蜜。甜到发齁，老北京人配茶吃。', where: '稻香村' },
    { key: 'food_kaikouxiao', name: '开口笑', en: 'Sesame Smiley', cat: 'sweet', courage: 1, when: '午',
      story: '滚满芝麻的小面团，炸到裂开像在笑。过年时家家都有一盘。', where: '稻香村' },
    { key: 'food_xingren', name: '杏仁豆腐', en: 'Almond Tofu', cat: 'sweet', courage: 1, when: '晚',
      story: '杏仁磨浆凝成的白玉，浇上糖水和桂花。夏天的一碗清凉。', where: '仿膳饭庄 · 老北京餐馆' },
    { key: 'food_chatang', name: '茶汤', en: 'Chatang', cat: 'drink', courage: 2, when: '早',
      story: '糜子面用大铜壶的开水一冲，撒红糖和果料。铜壶是龙头造型，冲茶汤本身就是一场表演。', where: '茶汤李 · 庙会' },
    { key: 'food_erguotou', name: '二锅头', en: 'Erguotou', cat: 'drink', courage: 4, when: '晚',
      story: '五十六度的高粱酒，红星、牛栏山。北京人管小瓶的叫"小二"，配羊蝎子或者一盘花生米。', where: '任何一家小馆' },
  ],
  foodMore: ['褡裢火烧','炒疙瘩','麻豆腐','糖耳朵','宫廷奶酪','京八件','面茶','北冰洋汽水','老北京酸奶','糖火烧','砂锅白肉','炒红果','乾隆白菜','炸咯吱','姜丝排叉','糖卷果','芸豆卷','奶油炸糕','艾窝窝','冰糖葫芦','豆腐脑','糖油饼','烧羊肉','酱牛肉','扒糕','萨其马','栗子面窝头','糖炒栗子','爆羊肉','酸梅汤','豆腐丝','煎饼馃子','肉末烧饼','烤鸭卷饼','羊肉汆面','榆钱糕','糖炒红果','炸酱鱼'],

  /* ===== 京剧脸谱 ===== */
  masks: [
    { key: 'red', name: '红脸', color: '#c8322b', accent: '#1a1a1a', role: '关羽', trait: '忠义 · 耿直',
      story: '红色代表忠勇正直。关公的卧蚕眉、丹凤眼，加上一部长髯，台上一出场，观众就知道这是义薄云天的人。' },
    { key: 'black', name: '黑脸', color: '#1a1a1a', accent: '#f4efe6', role: '包拯', trait: '铁面 · 无私',
      story: '黑色代表刚直不阿。包公额头上的月牙，传说是他能"日断阳、夜断阴"的印记。张飞也是黑脸，但多了几分莽撞。' },
    { key: 'white', name: '白脸', color: '#f4efe6', accent: '#1a1a1a', role: '曹操', trait: '奸诈 · 多疑',
      story: '白色代表阴险狡诈。曹操的白脸上只画细细的黑线，眼角向下——京剧用一张脸告诉你：这个人不可信。' },
    { key: 'blue', name: '蓝脸', color: '#2c5f9e', accent: '#f4efe6', role: '窦尔敦', trait: '刚强 · 桀骜',
      story: '蓝色代表勇猛刚烈，也带一点桀骜不驯。《盗御马》里的窦尔敦，一张蓝脸就是绿林好汉的身份证。' },
    { key: 'yellow', name: '黄脸', color: '#d9a520', accent: '#1a1a1a', role: '典韦', trait: '凶猛 · 暴躁',
      story: '黄色代表骁勇凶悍。曹操的贴身猛将典韦，双戟八十斤，脸谱也是一脸杀气。' },
    { key: 'gold', name: '金脸', color: '#c9a227', accent: '#7a1f1a', role: '二郎神', trait: '神佛 · 妖魔',
      story: '金色和银色专属于神仙、佛祖和妖怪。二郎神的金脸上还有第三只眼，一看便知不是凡人。' },
  ],

  /* ===== 北京话考试 ===== */
  quiz: [
    { q: '「这人真局气」——「局气」是什么意思？', a: ['讲义气、够意思', '爱较真儿', '拘谨、放不开', '脾气大'], c: 0, e: '「局气」是北京话里最高的夸奖之一：为人仗义、办事敞亮。' },
    { q: '「您猜怎么着？」——北京人说这句话时通常是？', a: ['真的在让你猜', '一句口头禅，接下来要讲事儿了', '生气了', '要跟你打赌'], c: 1, e: '这是典型的北京式开场白，相当于「你猜发生了什么」，后面一定跟着一段故事。' },
    { q: '「得嘞！」是什么意思？', a: ['得了吧', '好的、成了', '不行', '等一下'], c: 1, e: '「得嘞」= 好嘞、没问题。饭馆点完菜，服务员一句「得嘞」，就是接单了。' },
    { q: '「他早颠儿了」——「颠儿」是？', a: ['摔倒了', '疯了', '走了、跑了', '睡了'], c: 2, e: '「颠儿」就是走人、溜了。「颠儿了」带点儿轻快，不是逃跑那么严重。' },
    { q: '「怹」（tān）这个字用来称呼谁？', a: ['自己', '对方', '第三人的敬称', '小孩'], c: 2, e: '「怹」是「他」的敬称，老北京对长辈、尊敬的人才用。现在会说的人不多了。' },
    { q: '「盖了帽儿了」是在说？', a: ['戴帽子', '太棒了、没得比', '完蛋了', '下雨了'], c: 1, e: '「盖了帽儿了」= 好到了顶。据说来自篮球里的「盖帽」，也有人说是老北京早就有的说法。' },
    { q: '「他就是个二把刀」——「二把刀」指？', a: ['两把刀', '技术不精、半吊子', '很厉害', '爱吵架'], c: 1, e: '「二把刀」是说手艺不精、一知半解。来源据说是旧时厨房里的二厨。' },
    { q: '「撒丫子」是什么动作？', a: ['撒手', '撒腿就跑', '放鸭子', '摔跤'], c: 1, e: '「丫子」是脚，「撒丫子」就是撒开腿跑。「撒丫子颠儿了」= 拔腿就跑了。' },
    { q: '在北京请人让路，最地道的说法是？', a: ['让开', '劳驾 / 借光', '走开', '对不起'], c: 1, e: '「劳驾」「借光」是老北京的客气话，加上一个「您」，礼数就全了。' },
    { q: '「这里头有猫儿腻」——「猫儿腻」是？', a: ['猫的油脂', '小猫', '见不得人的勾当', '好东西'], c: 2, e: '「猫儿腻」指暗中的小动作、隐情。据说来自波斯语「马儿密」（秘密），也有说是从「猫溺」来的。' },
  ],

  /* ===== 二十四节气 · 北京 ===== */
  terms: [
    { name: '立春', m: 2, d: 4, custom: '咬春：春饼卷豆芽、酱肘子，再啃一口心里美萝卜。' },
    { name: '雨水', m: 2, d: 19, custom: '什刹海的冰开始化了，冰场收摊，一冬天的热闹散场。' },
    { name: '惊蛰', m: 3, d: 6, custom: '惊蛰吃梨，「离」开虫害。护城河边的柳树发芽。' },
    { name: '春分', m: 3, d: 21, custom: '竖蛋、放风筝。天坛外的沙燕风筝，一放就是一天。' },
    { name: '清明', m: 4, d: 5, custom: '踏青、插柳。老北京的寒食节要吃「寒食十三绝」：驴打滚、艾窝窝、姜丝排叉……' },
    { name: '谷雨', m: 4, d: 20, custom: '玉渊潭的樱花谢了，景山的牡丹开了。老北京讲究谷雨喝新茶。' },
    { name: '立夏', m: 5, d: 6, custom: '立夏称人、吃立夏蛋。胡同里的槐花开了，蒸槐花饭。' },
    { name: '小满', m: 5, d: 21, custom: '京郊的麦子灌浆，通惠河边可以看麦浪。' },
    { name: '芒种', m: 6, d: 6, custom: '煮青梅、送花神。《红楼梦》里大观园的姑娘们在这天祭饯花神。' },
    { name: '夏至', m: 6, d: 21, custom: '「冬至饺子夏至面」——一碗过水的炸酱面，配蒜。' },
    { name: '小暑', m: 7, d: 7, custom: '北海的荷花开了。晚上去后海划船，或者去天坛听蝉。' },
    { name: '大暑', m: 7, d: 23, custom: '喝信远斋的酸梅汤，吃冰碗。老北京的夏天靠一口冰镇的酸甜续命。' },
    { name: '立秋', m: 8, d: 8, custom: '贴秋膘：炙子烤肉、涮羊肉，立秋这天一定要吃肉。' },
    { name: '处暑', m: 8, d: 23, custom: '秋老虎。卖蝈蝈的又出现在胡同口，一个葫芦里养一只。' },
    { name: '白露', m: 9, d: 8, custom: '香山的叶子有了第一点红。早晚凉了，该收凉席了。' },
    { name: '秋分', m: 9, d: 23, custom: '中秋前后，兔儿爷摆上桌，自来红、自来白月饼上市。' },
    { name: '寒露', m: 10, d: 8, custom: '登高。八大处、香山、百望山，全城的人都去看红叶。' },
    { name: '霜降', m: 10, d: 23, custom: '钓鱼台的银杏黄了，糖炒栗子上市，柿子挂满枝头。' },
    { name: '立冬', m: 11, d: 7, custom: '立冬饺子。铜锅涮肉的季节正式开始。' },
    { name: '小雪', m: 11, d: 22, custom: '供暖了。屋里养一盆水仙，等它过年开花。' },
    { name: '大雪', m: 12, d: 7, custom: '什刹海冰场开了，冰车、冰鞋、冰上自行车。' },
    { name: '冬至', m: 12, d: 22, custom: '冬至饺子，数九开始。画一幅九九消寒图，每天涂一瓣梅花。' },
    { name: '小寒', m: 1, d: 6, custom: '腊八在小寒之后：腊八粥、腊八蒜，雍和宫排队舍粥。' },
    { name: '大寒', m: 1, d: 20, custom: '扫尘、写春联、买年货，等着过年。厂甸庙会要开了。' },
  ],

  /* ===== 行程规划器 ===== */
  planner: {
    interests: [
      { key: 'history', name: '历史古迹', icon: '宫' },
      { key: 'food', name: '地道美食', icon: '味' },
      { key: 'art', name: '艺术潮流', icon: '艺' },
      { key: 'nature', name: '山水园林', icon: '山' },
    ],
    templates: [
      { key: 'axis', name: '中轴线一日', tags: ['history', 'food'], base: 3,
        steps: [
          { t: '06:30', place: '天安门广场', note: '看升旗，然后去前门吃早点', tag: 'history' },
          { t: '08:30', place: '故宫', note: '从午门进、神武门出，至少留三小时', tag: 'history' },
          { t: '12:30', place: '四季民福 · 烤鸭', note: '故宫店能看到角楼，提前排队', tag: 'food' },
          { t: '14:30', place: '景山公园', note: '万春亭俯瞰整条中轴线', tag: 'nature' },
          { t: '16:30', place: '什刹海 · 烟袋斜街', note: '银锭桥看西山，钟鼓楼在旁边', tag: 'history' },
          { t: '19:00', place: '后海', note: '划船或者找一家有二胡的小馆', tag: 'food' },
        ] },
      { key: 'garden', name: '皇家园林一日', tags: ['nature', 'history'], base: 2,
        steps: [
          { t: '08:00', place: '颐和园', note: '东宫门进，长廊、佛香阁、十七孔桥', tag: 'nature' },
          { t: '12:00', place: '苏州街 · 听鹂馆', note: '园子里吃一顿宫廷菜', tag: 'food' },
          { t: '14:00', place: '圆明园', note: '西洋楼遗址，秋天有银杏', tag: 'history' },
          { t: '16:30', place: '北大未名湖', note: '博雅塔倒影，校园要预约', tag: 'nature' },
          { t: '19:00', place: '五道口', note: '大学生的夜生活', tag: 'food' },
        ] },
      { key: 'wall', name: '长城一日', tags: ['nature', 'history'], base: 2,
        steps: [
          { t: '07:00', place: '出发去慕田峪', note: '人比八达岭少，缆车上滑道下', tag: 'nature' },
          { t: '09:30', place: '慕田峪长城', note: '走到第 20 号敌楼，风景最好', tag: 'history' },
          { t: '13:00', place: '长城脚下 · 农家菜', note: '虹鳟鱼、柴鸡蛋、贴饼子', tag: 'food' },
          { t: '15:00', place: '明十三陵 · 长陵', note: '永乐皇帝的陵寝，神道两侧石像生', tag: 'history' },
          { t: '19:00', place: '簋街', note: '回城吃一顿麻小或羊蝎子', tag: 'food' },
        ] },
      { key: 'art', name: '艺术与现代一日', tags: ['art', 'food'], base: 2,
        steps: [
          { t: '08:00', place: '天坛', note: '看老北京晨练：抖空竹、踢毽子、唱戏', tag: 'history' },
          { t: '11:30', place: '老门框 · 爆肚', note: '前门附近的老字号小吃', tag: 'food' },
          { t: '13:30', place: '798 艺术区', note: 'UCCA、包豪斯厂房、涂鸦', tag: 'art' },
          { t: '17:00', place: '鸟巢 · 水立方', note: '天黑亮灯最好看', tag: 'art' },
          { t: '19:30', place: '三里屯', note: '太古里逛逛，晚上有 live house', tag: 'art' },
        ] },
      { key: 'hutong', name: '胡同市井一日', tags: ['food', 'history'], base: 2,
        steps: [
          { t: '07:30', place: '护国寺小吃', note: '豆汁儿焦圈、驴打滚、炒肝一次吃全', tag: 'food' },
          { t: '09:30', place: '钟鼓楼', note: '登鼓楼看击鼓表演，俯瞰胡同灰瓦', tag: 'history' },
          { t: '12:00', place: '方砖厂69号 · 炸酱面', note: '或者北新桥卤煮', tag: 'food' },
          { t: '14:00', place: '五道营 · 国子监', note: '租辆车骑一圈胡同', tag: 'history' },
          { t: '16:30', place: '雍和宫', note: '北京最大的藏传佛教寺院', tag: 'history' },
          { t: '19:00', place: '簋街 或 后海', note: '看你今晚想吃辣还是想吹风', tag: 'food' },
        ] },
      { key: 'museum', name: '博物馆一日', tags: ['history', 'art'], base: 1,
        steps: [
          { t: '09:00', place: '中国国家博物馆', note: '古代中国基本陈列，后母戊鼎', tag: 'history' },
          { t: '12:30', place: '前门 · 门框胡同', note: '褡裢火烧、炒肝、卤煮', tag: 'food' },
          { t: '14:00', place: '首都博物馆', note: '看北京城的建城史', tag: 'history' },
          { t: '17:00', place: '国家大剧院', note: '「巨蛋」在水里的倒影，晚上有演出', tag: 'art' },
        ] },
    ],
  },
};
